"""empty message

Revision ID: 75362bbb51f3
Revises: 66d1fac771e7
Create Date: 2019-08-30 23:40:46.529125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75362bbb51f3'
down_revision = '66d1fac771e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barrage', sa.Column('sex', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('barrage', 'sex')
    # ### end Alembic commands ###
